# Generated by Django 5.0 on 2024-01-30 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calapp', '0002_mainmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainmodel',
            old_name='name',
            new_name='inpname',
        ),
        migrations.RenameField(
            model_name='mainmodel',
            old_name='quant',
            new_name='inpquant',
        ),
    ]
