# Generated by Django 5.0 on 2024-02-02 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calapp', '0005_savemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savemodel',
            name='carbs',
        ),
        migrations.RemoveField(
            model_name='savemodel',
            name='fat',
        ),
        migrations.RemoveField(
            model_name='savemodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='savemodel',
            name='nutrients',
        ),
        migrations.RemoveField(
            model_name='savemodel',
            name='protien',
        ),
        migrations.RemoveField(
            model_name='savemodel',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='savemodel',
            name='vitamins',
        ),
        migrations.AddField(
            model_name='savemodel',
            name='consumedfood',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='calapp.calmodel'),
            preserve_default=False,
        ),
    ]
