# Generated by Django 5.0 on 2024-02-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calapp', '0006_remove_savemodel_carbs_remove_savemodel_fat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savemodel',
            name='quantity',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
