# Generated by Django 5.0 on 2024-02-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calapp', '0008_finalmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='calmodel',
            name='img',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='calmodel',
            name='type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
