# Generated by Django 5.0 on 2024-02-09 09:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calapp', '0010_finalmodel_img_finalmodel_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calmodel',
            name='favourite',
            field=models.ManyToManyField(blank=True, default=False, related_name='balabgt', to=settings.AUTH_USER_MODEL),
        ),
    ]
