# Generated by Django 5.0 on 2024-02-09 10:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calapp', '0011_calmodel_favourite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='calmodel',
            name='favourite',
            field=models.ManyToManyField(blank=True, default=False, related_name='favourites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='calmodel',
            name='img',
            field=models.ImageField(blank=True, upload_to='foodimg/'),
        ),
        migrations.AlterField(
            model_name='finalmodel',
            name='img',
            field=models.ImageField(blank=True, upload_to='foodimg/'),
        ),
    ]
