# Generated by Django 5.0 on 2024-02-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calapp', '0012_alter_calmodel_favourite_alter_calmodel_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calmodel',
            name='img',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
